// Copyright 2026 Simon Sagmeister
// This file was generated by: Open-Car-Dynamics/ros2/ocd_vehicle_nodes_cpp/tools/create_combinations.py
#include "ocd_vehicle_nodes_cpp/components.hpp"

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF52__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__Linear__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF_Simple__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF52__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__Linear__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF_Simple__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__SingleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF52__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__Linear__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF52__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__Linear__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  WheelTorque__PT1__DoubleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainWheelTorqueModel,
  tam::ocd::communication_handlers::DrivetrainWheelTorqueCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF52__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__Linear__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF_Simple__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF52__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__Linear__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF_Simple__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__SingleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsSingleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF52__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__Linear__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple_Extended__DefaultAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::DefaultAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF52__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF52)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__Linear__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::Linear)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple)

OCD_NODE_COMPONENT(
  Fx__PT1__DoubleTrack__MF_Simple_Extended__RideHeightAerodynamics,
  tam::ocd::drivetrain::DrivetrainFxModel,
  tam::ocd::communication_handlers::DrivetrainFxCommunicationHandler,
  tam::ocd::steering_actuator::PT1SteeringActuatorModel,
  tam::ocd::communication_handlers::SteeringActuatorPT1CommunicationHandler,
  tam::ocd::vehicle_dynamics::VehicleDynamicsDoubleTrackModel,
  tam::ocd::aerodynamics::RideHeightAerodynamicsModel, tam::ocd::tire_models::MF_Simple_Extended)

