import argparse
import re
import os
import sys

# Hardcoded workspace root (relative to this script)
WORKSPACE_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../../..'))

# Define your model class names as strings
drivetrains = [
    ("DrivetrainWheelTorqueModel", "DrivetrainWheelTorqueCommunicationHandler"),
    ("DrivetrainFxModel", "DrivetrainFxCommunicationHandler"),
    # Add more (Drivetrain, DrivetrainCommHandler) pairs here if needed
]

steering_actuators = [
    ("PT1SteeringActuatorModel", "SteeringActuatorPT1CommunicationHandler"),
    # Add more (SteeringActuator, SteeringActuatorCommHandler) pairs here if needed
]

vehicle_dynamics_models = [
    "VehicleDynamicsSingleTrackModel",
    "VehicleDynamicsDoubleTrackModel",
]

aerodynamics_models = [
    "DefaultAerodynamicsModel",
    "RideHeightAerodynamicsModel",
    # Add more aerodynamics models here if needed
]

tire_models = [
    "MF52",
    "Linear",
    "MF_Simple",
    "MF_Simple_Extended"
    # Add more tire models here if needed
]


def clean_name(name):
    # Remove keywords 'Model', 'Drivetrain', 'SteeringActuator' from each part
    parts = name.split("__")
    cleaned_parts = [
        re.sub(r"(Model|Drivetrain|SteeringActuator|VehicleDynamics)", "", part)
        for part in parts
    ]
    return "__".join(cleaned_parts)


def main():
    parser = argparse.ArgumentParser(description="Generate component combinations.")
    parser.add_argument(
        "--names-only", action="store_true", help="Print only the component names"
    )
    args = parser.parse_args()

    # Print header first
    if not args.names_only:
        script_abs_path = os.path.abspath(sys.argv[0])
        rel_path = os.path.relpath(script_abs_path, WORKSPACE_ROOT)
        print(f"// Copyright 2026 Simon Sagmeister")
        print(f"// This file was generated by: {rel_path}")
        print('#include "ocd_vehicle_nodes_cpp/components.hpp"\n')

    for drivetrain, drivetrain_comm in drivetrains:
        for steering, steering_comm in steering_actuators:
            for vdm in vehicle_dynamics_models:
                for aero in aerodynamics_models:
                    for tire in tire_models:
                        name = f"{drivetrain}__{steering}__{vdm}__{tire}__{aero}"
                        cleaned_name = clean_name(name)
                        if args.names_only:
                            print(cleaned_name)
                        else:
                            print(f"OCD_NODE_COMPONENT(")
                            print(f"  {cleaned_name},")
                            print(f"  tam::ocd::drivetrain::{drivetrain},")
                            print(
                                f"  tam::ocd::communication_handlers::{drivetrain_comm},"
                            )
                            print(f"  tam::ocd::steering_actuator::{steering},")
                            print(
                                f"  tam::ocd::communication_handlers::{steering_comm},"
                            )
                            print(f"  tam::ocd::vehicle_dynamics::{vdm},")
                            print(
                                f"  tam::ocd::aerodynamics::{aero}, tam::ocd::tire_models::{tire})\n"
                            )


if __name__ == "__main__":
    main()
