/simulation/VehicleModel:
  ros__parameters:
    aerodynamics:
      A_m2: 1.0
      c_d: 1.0
      c_l: -3.0
      d_aero_center_cog_m: 0.0
    delay:
      acceleration:
        actuation_delay_us: 10000
        initial_value: 0.0
      steering:
        actuation_delay_us: 50000
        initial_value: 0.0
    drivetrain:
      AccelBias_Front: 0.0
      BrakeBias_Front: 0.55
      I_wheel_front_kgm2: 1.2
      I_wheel_rear_kgm2: 1.4
      T_PT1_accel: 0.03
      m_vehicle_kg: 800.0
      tire_rolling_radius_front_m: 0.3
      tire_rolling_radius_rear_m: 0.3
    initial_state:
      drivetrain:
        a_x: 0.0
        omega_FL_radps: 0.0
        omega_FR_radps: 0.0
        omega_RL_radps: 0.0
        omega_RR_radps: 0.0
      steering_actuator:
        position_rad: 0.0
      vehicle_dynamics:
        alpha_tire_FL: 0.0
        alpha_tire_FR: 0.0
        alpha_tire_RL: 0.0
        alpha_tire_RR: 0.0
        kappa_tire_FL: 0.0
        kappa_tire_FR: 0.0
        kappa_tire_RL: 0.0
        kappa_tire_RR: 0.0
        phi_dot_radps: 0.0
        phi_rad: 0.0
        psi_dot_radps: 0.0
        psi_rad: 0.0
        theta_dot_radps: 0.0
        theta_rad: 0.0
        v_x_mps: 0.0
        v_y_mps: 0.0
        v_z_mps: 0.0
        v_z_w_FL_mps: 0.0
        v_z_w_FR_mps: 0.0
        v_z_w_RL_mps: 0.0
        v_z_w_RR_mps: 0.0
        x_m: 0.0
        y_m: 0.0
        z_m: 0.0
        z_w_FL_m: 0.0
        z_w_FR_m: 0.0
        z_w_RL_m: 0.0
        z_w_RR_m: 0.0
    integration_step_size_s: 0.0008
    steering_actuator:
      T_PT1: 0.05
      angle_max_rad: 0.3
      angle_rate_max_radps: 1.0
      static_offset_rad: 0.0
    vehicle_dynamics_double_track:
      I_x: 100.0
      I_y: 500.0
      I_z: 1000.0
      b_f: 1.6
      b_r: 1.5
      c_ar_f: 12000.0
      c_ar_r: 5000.0
      c_f: 120000.0
      c_r: 90000.0
      c_rr: 0.025
      c_t_f: 250000.0
      c_t_r: 250000.0
      d_f: 1300.0
      d_r: 900.0
      h_cg: 0.3
      h_pc_accel: 0.2
      h_pc_decel: 0.2
      h_rc: 0.2
      l: 3.2
      l_f: 1.8
      m: 800.0
      m_t_f: 15.0
      m_t_r: 15.0
      rr_w_f: 0.3
      rr_w_r: 0.3
      tire:
        front_left:
          FNOMIN: 3000.0
          LCX: 1.0
          LCY: 1.0
          LEX: 1.0
          LEY: 1.0
          LFZO: 1.0
          LGAX: 1.0
          LGAY: 1.0
          LGAZ: 1.0
          LGYR: 1.0
          LHX: 1.0
          LHY: 1.0
          LKX: 1.0
          LKY: 1.0
          LKYG: 1.0
          LMUX: 0.97
          LMUY: 0.97
          LMX: 1.0
          LMY: 1.0
          LRES: 1.0
          LS: 1.0
          LSGAL: 1.0
          LSGKP: 1.0
          LTR: 1.0
          LVMX: 1.0
          LVX: 1.0
          LVY: 1.0
          LVYKA: 1.0
          LXAL: 1.0
          LYKA: 1.0
          PCX1: 1.6
          PCY1: 1.5
          PDX1: 1.5
          PDX2: -0.04
          PDX3: 0.1
          PDY1: 1.2
          PDY2: -0.09
          PDY3: 0.1
          PEX1: 0.7
          PEX2: -0.17
          PEX3: 0.023
          PEX4: -0.14
          PEY1: 0.1
          PEY2: -1.2
          PEY3: 0.05
          PEY4: -8.1
          PEY5: 0.0
          PHX1: 0.0
          PHX2: 0.0
          PHY1: 0.003
          PHY2: -0.0006
          PHY3: 0.004
          PKX1: 30.7
          PKX2: 0.27
          PKX3: 0.13
          PKY1: -75.5
          PKY2: 4.65
          PKY3: -0.6
          PKY4: 2.0
          PKY5: 0.0
          PKY6: 0.0
          PKY7: 0.0
          PPY1: 0.0
          PPY2: 0.0
          PPY3: 0.0
          PPY4: 0.0
          PPY5: 0.0
          PTX1: 0.75
          PTX2: 0.007
          PTX3: -0.013
          PTY1: 3.8
          PTY2: 4.7
          PVX1: 0.0
          PVX2: 0.0
          PVY1: 0.04
          PVY2: -0.02
          PVY3: -0.97
          PVY4: -0.41
          RBX1: 17.4
          RBX2: 12.9
          RBX3: 0.0
          RBY1: 20.6
          RBY2: -23.5
          RBY3: 0.001
          RBY4: 0.0
          RCX1: 1.1
          RCY1: 1.0
          REX1: 0.0
          REX2: 0.0
          REY1: 0.0
          REY2: 0.0
          RHX1: 0.001
          RHY1: -0.02
          RHY2: 0.0
          RVY1: 0.16
          RVY2: 0.03
          RVY3: 27.5
          RVY4: -29.7
          RVY5: 0.03
          RVY6: 0.0
        front_right:
          FNOMIN: 3000.0
          LCX: 1.0
          LCY: 1.0
          LEX: 1.0
          LEY: 1.0
          LFZO: 1.0
          LGAX: 1.0
          LGAY: 1.0
          LGAZ: 1.0
          LGYR: 1.0
          LHX: 1.0
          LHY: 1.0
          LKX: 1.0
          LKY: 1.0
          LKYG: 1.0
          LMUX: 0.97
          LMUY: 0.97
          LMX: 1.0
          LMY: 1.0
          LRES: 1.0
          LS: 1.0
          LSGAL: 1.0
          LSGKP: 1.0
          LTR: 1.0
          LVMX: 1.0
          LVX: 1.0
          LVY: 1.0
          LVYKA: 1.0
          LXAL: 1.0
          LYKA: 1.0
          PCX1: 1.6
          PCY1: 1.5
          PDX1: 1.5
          PDX2: -0.04
          PDX3: 0.1
          PDY1: 1.2
          PDY2: -0.09
          PDY3: 0.1
          PEX1: 0.7
          PEX2: -0.17
          PEX3: 0.023
          PEX4: -0.14
          PEY1: 0.1
          PEY2: -1.2
          PEY3: 0.05
          PEY4: -8.1
          PEY5: 0.0
          PHX1: 0.0
          PHX2: 0.0
          PHY1: 0.003
          PHY2: -0.0006
          PHY3: 0.004
          PKX1: 30.7
          PKX2: 0.27
          PKX3: 0.13
          PKY1: -75.5
          PKY2: 4.65
          PKY3: -0.6
          PKY4: 2.0
          PKY5: 0.0
          PKY6: 0.0
          PKY7: 0.0
          PPY1: 0.0
          PPY2: 0.0
          PPY3: 0.0
          PPY4: 0.0
          PPY5: 0.0
          PTX1: 0.75
          PTX2: 0.007
          PTX3: -0.013
          PTY1: 3.8
          PTY2: 4.7
          PVX1: 0.0
          PVX2: 0.0
          PVY1: 0.04
          PVY2: -0.02
          PVY3: -0.97
          PVY4: -0.41
          RBX1: 17.4
          RBX2: 12.9
          RBX3: 0.0
          RBY1: 20.6
          RBY2: -23.5
          RBY3: 0.001
          RBY4: 0.0
          RCX1: 1.1
          RCY1: 1.0
          REX1: 0.0
          REX2: 0.0
          REY1: 0.0
          REY2: 0.0
          RHX1: 0.001
          RHY1: -0.02
          RHY2: 0.0
          RVY1: 0.16
          RVY2: 0.03
          RVY3: 27.5
          RVY4: -29.7
          RVY5: 0.03
          RVY6: 0.0
        rear_left:
          FNOMIN: 3000.0
          LCX: 1.0
          LCY: 1.0
          LEX: 1.0
          LEY: 1.0
          LFZO: 1.0
          LGAX: 1.0
          LGAY: 1.0
          LGAZ: 1.0
          LGYR: 1.0
          LHX: 1.0
          LHY: 1.0
          LKX: 1.0
          LKY: 1.0
          LKYG: 1.0
          LMUX: 0.97
          LMUY: 0.97
          LMX: 1.0
          LMY: 1.0
          LRES: 1.0
          LS: 1.0
          LSGAL: 1.0
          LSGKP: 1.0
          LTR: 1.0
          LVMX: 1.0
          LVX: 1.0
          LVY: 1.0
          LVYKA: 1.0
          LXAL: 1.0
          LYKA: 1.0
          PCX1: 1.6
          PCY1: 1.5
          PDX1: 1.5
          PDX2: -0.04
          PDX3: 0.1
          PDY1: 1.2
          PDY2: -0.09
          PDY3: 0.1
          PEX1: 0.7
          PEX2: -0.17
          PEX3: 0.023
          PEX4: -0.14
          PEY1: 0.1
          PEY2: -1.2
          PEY3: 0.05
          PEY4: -8.1
          PEY5: 0.0
          PHX1: 0.0
          PHX2: 0.0
          PHY1: 0.003
          PHY2: -0.0006
          PHY3: 0.004
          PKX1: 30.7
          PKX2: 0.27
          PKX3: 0.13
          PKY1: -75.5
          PKY2: 4.65
          PKY3: -0.6
          PKY4: 2.0
          PKY5: 0.0
          PKY6: 0.0
          PKY7: 0.0
          PPY1: 0.0
          PPY2: 0.0
          PPY3: 0.0
          PPY4: 0.0
          PPY5: 0.0
          PTX1: 0.75
          PTX2: 0.007
          PTX3: -0.013
          PTY1: 3.8
          PTY2: 4.7
          PVX1: 0.0
          PVX2: 0.0
          PVY1: 0.04
          PVY2: -0.02
          PVY3: -0.97
          PVY4: -0.41
          RBX1: 17.4
          RBX2: 12.9
          RBX3: 0.0
          RBY1: 20.6
          RBY2: -23.5
          RBY3: 0.001
          RBY4: 0.0
          RCX1: 1.1
          RCY1: 1.0
          REX1: 0.0
          REX2: 0.0
          REY1: 0.0
          REY2: 0.0
          RHX1: 0.001
          RHY1: -0.02
          RHY2: 0.0
          RVY1: 0.16
          RVY2: 0.03
          RVY3: 27.5
          RVY4: -29.7
          RVY5: 0.03
          RVY6: 0.0
        rear_right:
          FNOMIN: 3000.0
          LCX: 1.0
          LCY: 1.0
          LEX: 1.0
          LEY: 1.0
          LFZO: 1.0
          LGAX: 1.0
          LGAY: 1.0
          LGAZ: 1.0
          LGYR: 1.0
          LHX: 1.0
          LHY: 1.0
          LKX: 1.0
          LKY: 1.0
          LKYG: 1.0
          LMUX: 0.97
          LMUY: 0.97
          LMX: 1.0
          LMY: 1.0
          LRES: 1.0
          LS: 1.0
          LSGAL: 1.0
          LSGKP: 1.0
          LTR: 1.0
          LVMX: 1.0
          LVX: 1.0
          LVY: 1.0
          LVYKA: 1.0
          LXAL: 1.0
          LYKA: 1.0
          PCX1: 1.6
          PCY1: 1.5
          PDX1: 1.5
          PDX2: -0.04
          PDX3: 0.1
          PDY1: 1.2
          PDY2: -0.09
          PDY3: 0.1
          PEX1: 0.7
          PEX2: -0.17
          PEX3: 0.023
          PEX4: -0.14
          PEY1: 0.1
          PEY2: -1.2
          PEY3: 0.05
          PEY4: -8.1
          PEY5: 0.0
          PHX1: 0.0
          PHX2: 0.0
          PHY1: 0.003
          PHY2: -0.0006
          PHY3: 0.004
          PKX1: 30.7
          PKX2: 0.27
          PKX3: 0.13
          PKY1: -75.5
          PKY2: 4.65
          PKY3: -0.6
          PKY4: 2.0
          PKY5: 0.0
          PKY6: 0.0
          PKY7: 0.0
          PPY1: 0.0
          PPY2: 0.0
          PPY3: 0.0
          PPY4: 0.0
          PPY5: 0.0
          PTX1: 0.75
          PTX2: 0.007
          PTX3: -0.013
          PTY1: 3.8
          PTY2: 4.7
          PVX1: 0.0
          PVX2: 0.0
          PVY1: 0.04
          PVY2: -0.02
          PVY3: -0.97
          PVY4: -0.41
          RBX1: 17.4
          RBX2: 12.9
          RBX3: 0.0
          RBY1: 20.6
          RBY2: -23.5
          RBY3: 0.001
          RBY4: 0.0
          RCX1: 1.1
          RCY1: 1.0
          REX1: 0.0
          REX2: 0.0
          REY1: 0.0
          REY2: 0.0
          RHX1: 0.001
          RHY1: -0.02
          RHY2: 0.0
          RVY1: 0.16
          RVY2: 0.03
          RVY3: 27.5
          RVY4: -29.7
          RVY5: 0.03
          RVY6: 0.0

